name: Just Checkout with condition

on:
  workflow_dispatch:
  pull_request:
    types: [opened]
    paths: ['Assets\Resources\Characters\BlueArchive\**', 'Assets/Resources/Characters/BlueArchive/**']
    
jobs:
  run-ls:
    runs-on: self-hosted
    # チェックアウトのみ実行
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

