name: Get modified or added directory

on:
  pull_request:
    types: [opened]

jobs:
  get_target_scene:
    runs-on: self-hosted

    steps:
    # プルリクエストにおけるコミットの深さの計算
    - name: Get commit depth
      id: commit_depth
      run: echo "fetch_depth=$(( commits +1 ))" >> $GITHUB_ENV
      env:
        commits: ${{ github.event.pull_request.commits }}


    # リポジトリのチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ env.fetch_depth }}

    # 変更されたまたは追加された、Assets/Resources/CharactersかAssets/Resources/Props以下のディレクトリを取得
    - name: Get modified or added directory
      id: get_target_directory
      run: |

        $TARGET_DIRECTORY = git diff origin/develop...origin/${{ github.head_ref }} --name-only | Select-String -Pattern 'Assets/Resources/Characters|Assets/Resources/Props' | ForEach-Object { Split-Path $_.Line }

        if (-not $TARGET_DIRECTORY) {
            Write-Host "No directory found in the modified or added files."
            exit 1
        }

        $env:TARGET_DIRECTORY = $TARGET_DIRECTORY
        Add-Content -Path $env:GITHUB_ENV -Value "target_directory=$TARGET_DIRECTORY"

    # プルリクエストに変更/追加されたディレクトリをコメント
    - name: Comment on pull request
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          The following directories have been modified or added in this pull request:
          ${{ env.target_directory }}
        token: ${{ secrets.GITHUB_TOKEN }}
