name: Get modified or added directory

on:
  pull_request:
    types: [opened]
    # paths:
    #   - ['Assets/Resources/Characters/**']
      

jobs:
  get_target_scene:
    runs-on: self-hosted

    steps:
    # リポジトリのチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # 変更ファイルの確認
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45

    # 変更ファイルのディレクトリ名を取得
    - name: Get directory name
      id: get_directory_name
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        $allChangedFiles = $env:ALL_CHANGED_FILES -split "`n"  # 改行で分割して配列に
        $filesAsString = ($allChangedFiles -join ",")  # カンマで結合して文字列に
        Write-Host "Files as string: $filesAsString"

        Add-Content -Path $env:GITHUB_ENV -Value "changed_files=$filesAsString"

    # プルリクエストに変更/追加されたディレクトリをコメント
    - name: Comment on pull request
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          The following directories have been modified or added in this pull request:
          ${{ env.changed_files }}
        token: ${{ secrets.GITHUB_TOKEN }}
