name: Get modified or added directory

on:
  pull_request:
    types: [opened]
      

jobs:
  get_target_scene:
    runs-on: self-hosted

    steps:
    # リポジトリのチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # 変更ファイルの確認
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45

    # 変更されたファイルのあるディレクトリ名(Assets/Resources/Characters/BlueArchive/CharacterName/DirectoryName/filenameにあるCharacterName)を取得
    - name: Get directory name
      id: get_directory_name
      shell: powershell
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        $changed_files = $env:ALL_CHANGED_FILES -split '\r?\n'
        $changed_directories = @()
        foreach ($file in $changed_files) {
            $file_trimmed = $file -replace 'Assets\\Resources\\Characters\\BlueArchive\\', ''
            $directory = $file_trimmed -split '\\' | Select-Object -First 1
            $changed_directories += $directory
        }

        $changed_directories = $changed_directories | Sort-Object -Unique
        Add-Content -Path $env:GITHUB_ENV -Value "changed_directories=$changed_directories"

    # Unityエディタ再生を実行するシーンのパスを取得
    - name: Execute Unity Editor Play
      run: |
        $changed_directories = $env:changed_directories
        foreach ($directory in $changed_directories) {
            .github/auto-record.ps1 "Assets/Resources/Characters/BlueArchive/$directory/Scenes/SetupScene.unity"
        }

    # 書き出したファイルの移動
    - name: Move artifacts
      run: .github/move-ref.ps1 ${{ github.event.pull_request.number }}

    # プルリクエストに変更/追加されたディレクトリをコメント
    - name: Comment on pull request
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          The following directories have been modified or added in this pull request:
          "G:\\マイドライブ\\Share\\${{ github.event.pull_request.number }}"
        token: ${{ secrets.GITHUB_TOKEN }}
