name: Post Image to Linked Issue

on:
  pull_request:
    types: [opened]

jobs:
  post_image_to_issue:
    runs-on: self-hosted  # セルフホステッドランナーで実行

    steps:
    # リポジトリのチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # 画像をアーティファクトとしてアップロード
    - name: Upload Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pr-image-artifact
        path: "C:\\artifacts\\*.mp4"  # 特定ディレクトリ内の画像と動画をアップロード

    # アーティファクトのダウンロードリンクを作成して、イシューにコメントを投稿
    - name: Post image link to linked issue
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          The image artifact is available for download.
          [Download Image Artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        token: ${{ secrets.GITHUB_TOKEN }}

    # ディレクトリの中を削除
    - name: Remove artifacts
      run: Remove-Item -Path "C:\\artifacts\\*.mp4" -Recurse -Force
