name: Post Image to Linked Issue

on:
  pull_request:
    types: [opened]

jobs:
  post_image_to_issue:
    runs-on: self-hosted  # セルフホステッドランナーで実行

    steps:
    # リポジトリのチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # echoコマンドを実行
    - name: Execute echo command
      run: echo "Hello, this is a command execution on self-hosted runner!"
    
    # 画像をアーティファクトとしてアップロード
    - name: Upload Image Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pr-image-artifact
        path: "C:\\artifacts\\hoge3.webp"  # セルフホステッドランナー上の画像のパスを指定

    # アーティファクトのダウンロードリンクを作成して、イシューにコメントを投稿
    - name: Post image link to linked issue
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          The image has been uploaded as an artifact. You can download it from the following link:

          [Download Image Artifact](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        token: ${{ secrets.GITHUB_TOKEN }}
